logging.level:
  root: warn
  br.ufrrj.labweb.campussocial: debug
  org.springframework:
    data: info
    data.elasticsearch: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campsocialdb
    username: postgres
    password: postgres
  
br:
  ufrrj:
    labweb:
      campussocial:
        elastic-search-host: localhost:9200
